apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogIlkyaGhjMmhqYUdsdVlXeGxlRHBuYUhCZlZubFBkMDE1YWpGelNFeEpiV3BEWTA5Tk4xQllTREJGVkdSSFZEVXhNbGhFZERWYSIKCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
