apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogeyJhdXRoIjogIlkyaGhjMmhqYUdsdVlXeGxlRHBuYUhCZllYa3djbFJOUkV0dU9YUmtSV1E0U0doNFdGVlBPR3RsWkZGdlNuSTRNWEZ1TUdsQyJ9Cgl9LAoJImNyZWRzU3RvcmUiOiAib3N4a2V5Y2hhaW4iCn0=
type: kubernetes.io/dockerconfigjson
