apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZMmhoYzJoamFHbHVZV3hsZURwbmFIQmZWbmxPZE15ajFzSExJbWpDY09NN1BYSDBFVGRHVDUxWER0NVoiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
