apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZMmhoYzJoamFHbHVZV3hsZURwbmFIQmZZWGt3Y2xSTlJFdHVPWFJrUldRNFNHaDRXRlZQT0d0bFpGRnZTbkk0TVhGdU1HbEMiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
