apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZMmhoYzJoamFHbHVZV3hsZURwbmFIQmZWbmxWbmxQZEt1ajFzSExJbWpDY09NN1BYSDBFVGRHVDUxWER0NVoiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
